language: node_js
branches:
  only:
  - "gh-pages"
  - /dev-(.*)/
node_js:
  - "7"
  - "6"
  - "5"
  - "4"

before_script:
  - npm install
  - npm install grunt-cli -g

script:
  - grunt

sudo: false
